---
title: "About Our Lab"
author: "Colleen Gerrity and Matthew Olimb"
date: "12/7/2020"
output: "html_document"
---

Welcome to the Computational Social Neuroscience Group at George Mason University. 

We are a multidisciplinary group with focuses in neuroscience, psychology, and programming. We employ many methods such as online research, Electroencepolgraphy, and Functional Magnetic Resonance Imaging in our research. Our lab is made up of a range of diverse thinkers from our Principle Investigator, Jim Thompson, to our ever friendly and helpful Research Assistants. At CSNG we value:
The core values of the CSNG are 

- Inclusiveness (everyone’s voice counts)
- Multi-disciplinary focus (integrate different disciplines into our research goals)
- Diversity (value and respect differences in perspectives and opinions)
- Integrity (follow strict institutional, scientific, and ethical guidelines)
- Productivity (input our highest efforts to reach our goals)
- Innovation (remain open-minded, and learn from both successes and failures)
- Excellence (target the highest quality of scientific research)
- Collaboration (what is done in isolation is often accomplished better in partnership)
- Leadership (nourish from a culture of intra and inter-motivation and inspiration)

We feel that these Core Values are vital to success in science, and it is important that every member of the CSNG strive to fulfill them at all times.

This website was inspired by several others, and borrows heavily from them. It’s also a work in progress; therefore, updates are implemented as we move forward. 


 
---

## Lab Announcements 

- Announcement 1

- Announcement 2